version: '3.8'

services:
  app:
    build: .
    container_name: auth.zed31rus.ru
    ports:
      - "3003:3003"
    env_file:
      - ./.env
    volumes:
      - ./prisma:/app/prisma
      - ./static/:/app/static
    restart: always
